import groovy.json.JsonSlurper
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

abstract class GenerateIOSProductFeatureBundles : DefaultTask() {
    @get:InputFile
    abstract val inputFile: RegularFileProperty

    @get:OutputFile
    abstract val productBundleOutputFile: RegularFileProperty

    @get:OutputDirectory
    abstract val iosAppDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        @Suppress("UNCHECKED_CAST")
        val config = JsonSlurper().parse(inputFile.get().asFile) as Map<String, Any>

        @Suppress("UNCHECKED_CAST")
        val products = config["products"] as List<Map<String, Any>>

        @Suppress("UNCHECKED_CAST")
        val featureSwiftTargets = config["featureSwiftTargets"] as Map<String, Map<String, String>>

        fun swiftArray(values: Any?): String =
            (values as List<*>).joinToString(prefix = "[", postfix = "]") { "\"$it\"" }

        val constants = products.joinToString("\n\n") { product ->
            val swiftName = product.getValue("swiftName")
            """
            |    static let $swiftName = ProductFeatureBundle(
            |        productId: "${product.getValue("productId")}",
            |        displayName: "${product.getValue("displayName")}",
            |        supportedExperiences: ${swiftArray(product["supportedExperiences"])},
            |        bundledFeatures: ${swiftArray(product["bundledFeatures"])}
            |    )
            """.trimMargin()
        }

        val productBundleFile = productBundleOutputFile.get().asFile
        productBundleFile.parentFile.mkdirs()
        productBundleFile.writeText(
            """
            |// Generated by ./gradlew generateIOSProductFeatureBundles.
            |// Source: config/product-feature-bundles.json
            |
            |import Foundation
            |
            |struct ProductFeatureBundle: Equatable, Sendable {
            |    let productId: String
            |    let displayName: String
            |    let supportedExperiences: [String]
            |    let bundledFeatures: [String]
            |}
            |
            |enum ProductFeatureBundles {
            |$constants
            |}
            |
            """.trimMargin(),
        )

        products.forEach { product ->
            val swiftName = product.getValue("swiftName")
            val registryFile = iosAppDirectory.get()
                .file(product.getValue("iosFeatureRegistryFile").toString())
                .asFile
            val bundledFeatures = product["bundledFeatures"] as List<*>
            val modules = bundledFeatures.joinToString("\n") { feature ->
                val moduleName = featureSwiftTargets
                    .getValue(feature.toString())
                    .getValue("moduleName")
                "            $moduleName.module,"
            }

            registryFile.parentFile.mkdirs()
            registryFile.writeText(
                """
                |// Generated by ./gradlew generateIOSProductFeatureBundles.
                |// Source: config/product-feature-bundles.json
                |
                |@MainActor
                |extension CommerceFeatureRegistry {
                |    static let $swiftName = CommerceFeatureRegistry(
                |        modules: [
                |$modules
                |        ]
                |    )
                |}
                |
                """.trimMargin(),
            )
        }
    }
}

plugins {
    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidMultiplatformLibrary) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.metro) apply false
    alias(libs.plugins.skie) apply false
}

tasks.register<GenerateIOSProductFeatureBundles>("generateIOSProductFeatureBundles") {
    inputFile.set(layout.projectDirectory.file("config/product-feature-bundles.json"))
    productBundleOutputFile.set(
        layout.projectDirectory.file("iosApp/SharedIOS/Core/ProductFeatureBundles.generated.swift"),
    )
    iosAppDirectory.set(layout.projectDirectory.dir("iosApp"))
}
