import groovy.json.JsonSlurper

plugins {
    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidMultiplatformLibrary) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.metro) apply false
    alias(libs.plugins.skie) apply false
}

tasks.register("generateIOSProductFeatureBundles") {
    val inputFile = layout.projectDirectory.file("config/product-feature-bundles.json")
    val outputFile = layout.projectDirectory.file("iosApp/SharedIOS/ProductFeatureBundles.generated.swift")

    inputs.file(inputFile)
    outputs.file(outputFile)

    doLast {
        @Suppress("UNCHECKED_CAST")
        val products = (
            JsonSlurper().parse(inputFile.asFile) as Map<String, Any>
        )["products"] as List<Map<String, Any>>

        fun swiftArray(values: Any?): String =
            (values as List<*>).joinToString(prefix = "[", postfix = "]") { "\"$it\"" }

        val constants = products.joinToString("\n\n") { product ->
            val swiftName = product.getValue("swiftName")
            """
            |    static let $swiftName = ProductFeatureBundle(
            |        productId: "${product.getValue("productId")}",
            |        displayName: "${product.getValue("displayName")}",
            |        supportedExperiences: ${swiftArray(product["supportedExperiences"])},
            |        bundledFeatures: ${swiftArray(product["bundledFeatures"])}
            |    )
            """.trimMargin()
        }

        outputFile.asFile.writeText(
            """
            |// Generated by ./gradlew generateIOSProductFeatureBundles.
            |// Source: config/product-feature-bundles.json
            |
            |import Foundation
            |
            |struct ProductFeatureBundle: Equatable, Sendable {
            |    let productId: String
            |    let displayName: String
            |    let supportedExperiences: [String]
            |    let bundledFeatures: [String]
            |}
            |
            |enum ProductFeatureBundles {
            |$constants
            |}
            |
            """.trimMargin(),
        )
    }
}
