// Generated by ./gradlew generateIOSProductFeatureBundles.
// Source: config/product-feature-bundles.json

@MainActor
extension CommerceFeatureRegistry {
    static let appTwo = CommerceFeatureRegistry(
        modules: [
            OrdersFeatureModule.module,
            ListsFeatureModule.module,
            DeliveryFeatureModule.module,
        ]
    )
}
