// Generated by ./gradlew generateIOSProductFeatureBundles.
// Source: config/product-feature-bundles.json

import Foundation

struct ProductFeatureBundle: Equatable, Sendable {
    let productId: String
    let displayName: String
    let supportedExperiences: [String]
    let bundledFeatures: [String]
}

enum ProductFeatureBundles {
    static let appOne = ProductFeatureBundle(
        productId: "AppOneStandalone",
        displayName: "AppOne",
        supportedExperiences: ["shop"],
        bundledFeatures: ["orders", "catalog", "product-details", "delivery"]
    )

    static let appTwo = ProductFeatureBundle(
        productId: "AppTwoStandalone",
        displayName: "AppTwo",
        supportedExperiences: ["newport-buckhead"],
        bundledFeatures: ["orders", "lists", "delivery"]
    )

    static let superApp = ProductFeatureBundle(
        productId: "SuperApp",
        displayName: "Super App",
        supportedExperiences: ["newport-buckhead", "shop"],
        bundledFeatures: ["orders", "lists", "catalog", "product-details", "delivery"]
    )
}
